### ISSUE TITLE
Multiple offline update on same item not all synced

### ISSUE THREAD

**Issue by mathieuedet** [aws-amplify/amplify-android#1288]
I'm developing Android app with offline support. In online use-case, no problem.
Unfortunately, when I test an offline scenario, I encountering a bug during multiple updates on same item.

After each updates, I log local object and all fields values are ok (last edition values with new editions)

Example with fake data : 

Original : 

```
{
"name": "value1",
"nickname": "mat",
"age": 27,
"city": "Paris"
}
```

Update name and city offline :
```
{
"name": "value2",
"nickname": "mat",
"age": 27,
"city": "London"
}
```

Update age offline too :
```
{
"name": "value2",
"nickname": "mat",
"age": 28,
"city": "London"
}
```

When I request my object from Datastore, I get updated object from my local version

When connection is established, I use `Datastore.start` to sync data.

However, pushed object contains only last update :

```
{
"name": "value1",
"nickname": "mat"
"age": 28,
"city": "London"
}
```

Problem occurs on 1.17.2 and 1.17.3 versions but **not on 1.6.9**. I cannot use 1.6.9 because of some bugs on this version.

Thanks

**Comment by shantanu-csedu** [comment]
For my case, every column reset to null except the ID. This bug was introduced in version 1.17.2 and still exists in 1.17.5.

**Comment by whisller** [comment]
@richardmcclellan any update on this issue? We're experiencing same problem.

**Comment by whisller** [comment]
It seems that fix merged by @sdhuka is working on our side. Thanks everyone!

**Comment by richardmcclellan** [comment]
This issue has been resolved with the [Amplify Android 1.19.0](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.19.0) release!

**Comment by shantanu-csedu** [comment]
Issue still exists in version 1.19.0. It's less frequent but still happening

**Comment by richardmcclellan** [comment]
@shantanu-csedu can you please provide specific steps to reproduce?

**Comment by shantanu-csedu** [comment]
Steps to reproduce the bugs:
1. Force stop app and open (so that amplify sync trigger by query or manually)
2. Create a row and update at least once before sync started (while amplify sync is checking network states and it takes around 20 seconds)
3. After sync ends, newly created row data will be empty except the primary key

Note: it will happen after the sync started but it's hard to reproduce.

**Comment by richardmcclellan** [comment]
Thanks for the clarification @shantanu-csedu - I believe we fixed the "update followed by update" scenario, but the it sounds like the same issue exists for "create followed by update".  We will take another look.

**Comment by richardmcclellan** [comment]
@shantanu-csedu your issue has been fixed in the [Amplify Android 1.20.0 release](https://github.com/aws-amplify/amplify-android/releases/tag/release_v1.20.0).  Please let us know if any additional issues arise!
