### ISSUE TITLE
[DataStore] Model cannot be synced to cloud due to index field is null

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-android#1461]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java, Kotlin

### Amplify Categories

DataStore

### Gradle script dependencies

<details>

```groovy
// Put output below this line
dependencies {
    implementation 'androidx.appcompat:appcompat:1.3.0'
    implementation 'com.google.android.material:material:1.3.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
    implementation 'com.amplifyframework:aws-api:1.24.1'
    implementation 'com.amplifyframework:aws-datastore:1.24.1'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}

```

</details>

### Environment information

<details>

```
# Put output below this line
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          1.8.0_292 (AdoptOpenJDK 25.292-b10)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

When saving a model with below schema, if the index field is not assigned, model can only be saved into local DB, but failed syncing to DynamoDB. In addition, amplify-ios doesn't report the underlying GraphQL error on invoking `DataStore.save` API.

```graphql
type TestModel @model @key(name: "parent-id-index", fields: ["parentId"]) {
  id: ID!
  content: String!
  parentId: ID
}
```

Original issue please refer to https://github.com/aws-amplify/amplify-flutter/issues/306#issuecomment-904230597
Same issue in amplify-ios:  https://github.com/aws-amplify/amplify-ios/issues/1390

### Reproduction steps (if applicable)

1. Create a minimal iOS App with above mentioned model schema
2. Create a model without assigning the `parentId` field
3. Save model
4. Observe

### Code Snippet

```java
// Put your code below this line.
        TestModel testModel = TestModel.builder()
                .content("Test model android")
                .build();
        Amplify.DataStore.save(testModel,
                success -> Log.i("Tutorial", "Saved item: " + success.item().getContent()),
                error -> Log.e("Tutorial", "Could not save item to DataStore", error)
                );
```

### Log output

<details>

```
// Put your logs below this line
I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
I/Tutorial: TestModel {id=823c6aad-cfc7-4e36-af86-d170812fdf03, content=Test model android, parentId=null, createdAt=null, updatedAt=null}
I/Tutorial: Saved item: Test model android
I/Tutorial: Record{id='dec4b576-0479-11ec-b744-9fe25688c16f', containedModelId='823c6aad-cfc7-4e36-af86-d170812fdf03', serializedMutationData='{"modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"mutatedItem":{"id":"823c6aad-cfc7-4e36-af86-d170812fdf03","modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"serializedData":{"createdAt":null,"id":"823c6aad-cfc7-4e36-af86-d170812fdf03","content":"Test model android","parentId":null,"updatedAt":null}},"mutationId":dec4b576-0479-11ec-b744-9fe25688c16f,"mutationType":"CREATE","predicate":{"_type":"ALL"}}', containedModelClassName='com.amplifyframework.core.model.SerializedModel'}
I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=SerializedModel{id='823c6aad-cfc7-4e36-af86-d170812fdf03', serializedData={createdAt=null, id=823c6aad-cfc7-4e36-af86-d170812fdf03, content=Test model android, parentId=null, updatedAt=null}, modelName=TestModel}, mutationType=CREATE, mutationId=dec4b576-0479-11ec-b744-9fe25688c16f, predicate=MatchAllQueryPredicate}
I/Tutorial: Record{id='dec4b576-0479-11ec-b744-9fe25688c16f', containedModelId='823c6aad-cfc7-4e36-af86-d170812fdf03', serializedMutationData='{"modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"mutatedItem":{"id":"823c6aad-cfc7-4e36-af86-d170812fdf03","modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"serializedData":{"createdAt":null,"id":"823c6aad-cfc7-4e36-af86-d170812fdf03","content":"Test model android","parentId":null,"updatedAt":null}},"mutationId":dec4b576-0479-11ec-b744-9fe25688c16f,"mutationType":"CREATE","predicate":{"_type":"ALL"}}', containedModelClassName='com.amplifyframework.core.model.SerializedModel'}
I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=SerializedModel{id='823c6aad-cfc7-4e36-af86-d170812fdf03', serializedData={createdAt=null, id=823c6aad-cfc7-4e36-af86-d170812fdf03, content=Test model android, parentId=null, updatedAt=null}, modelName=TestModel}, mutationType=CREATE, mutationId=dec4b576-0479-11ec-b744-9fe25688c16f, predicate=MatchAllQueryPredicate}
I/amplify:aws-datastore: Orchestrator lock acquired.
I/amplify:aws-datastore: Orchestrator lock released.
I/Tutorial: TestModel {id=4fd52932-3155-4c9f-ab85-99d09cb07a15, content=Test model android, parentId=null, createdAt=null, updatedAt=null}
I/Tutorial: Saved item: Test model android
I/Tutorial: Record{id='df486467-0479-11ec-b744-99c4fba2abda', containedModelId='4fd52932-3155-4c9f-ab85-99d09cb07a15', serializedMutationData='{"modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"mutatedItem":{"id":"4fd52932-3155-4c9f-ab85-99d09cb07a15","modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"serializedData":{"createdAt":null,"id":"4fd52932-3155-4c9f-ab85-99d09cb07a15","content":"Test model android","parentId":null,"updatedAt":null}},"mutationId":df486467-0479-11ec-b744-99c4fba2abda,"mutationType":"CREATE","predicate":{"_type":"ALL"}}', containedModelClassName='com.amplifyframework.core.model.SerializedModel'}
I/amplify:aws-datastore: Successfully enqueued PendingMutation{mutatedItem=SerializedModel{id='4fd52932-3155-4c9f-ab85-99d09cb07a15', serializedData={createdAt=null, id=4fd52932-3155-4c9f-ab85-99d09cb07a15, content=Test model android, parentId=null, updatedAt=null}, modelName=TestModel}, mutationType=CREATE, mutationId=df486467-0479-11ec-b744-99c4fba2abda, predicate=MatchAllQueryPredicate}
I/Tutorial: Record{id='df486467-0479-11ec-b744-99c4fba2abda', containedModelId='4fd52932-3155-4c9f-ab85-99d09cb07a15', serializedMutationData='{"modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"mutatedItem":{"id":"4fd52932-3155-4c9f-ab85-99d09cb07a15","modelSchema":{"associations":{},"authRules":[],"fields":{"content":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"content","targetType":"String"},"createdAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"createdAt","targetType":"AWSDateTime"},"id":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":true,"javaClassForValue":"java.lang.String","name":"id","targetType":"ID"},"parentId":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":false,"isRequired":false,"javaClassForValue":"java.lang.String","name":"parentId","targetType":"ID"},"updatedAt":{"authRules":[],"isArray":false,"isEnum":false,"isModel":false,"isReadOnly":true,"isRequired":false,"javaClassForValue":"com.amplifyframework.core.model.temporal.Temporal$DateTime","name":"updatedAt","targetType":"AWSDateTime"}},"indexes":{"parent-id-index":{"indexFieldNames":["parentId"],"indexName":"parent-id-index"}},"modelClass":"com.amplifyframework.datastore.generated.model.TestModel","name":"TestModel","pluralName":"TestModels"},"serializedData":{"createdAt":null,"id":"4fd52932-3155-4c9f-ab85-99d09cb07a15","content":"Test model android","parentId":null,"updatedAt":null}},"mutationId":df486467-0479-11ec-b744-99c4fba2abda,"mutationType":"CREATE","predicate":{"_type":"ALL"}}', containedModelClassName='com.amplifyframework.core.model.SerializedModel'}
I/amplify:aws-datastore: Successfully removed from mutations outboxPendingMutation{mutatedItem=SerializedModel{id='4fd52932-3155-4c9f-ab85-99d09cb07a15', serializedData={createdAt=null, id=4fd52932-3155-4c9f-ab85-99d09cb07a15, content=Test model android, parentId=null, updatedAt=null}, modelName=TestModel}, mutationType=CREATE, mutationId=df486467-0479-11ec-b744-99c4fba2abda, predicate=MatchAllQueryPredicate}


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

### Additional information and screenshots

GraphQL request when saving the model

```json
{
	"query": "mutation CreateTestModel($input: CreateTestModelInput!) {\n  createTestModel(input: $input) {\n    _deleted\n    _lastChangedAt\n    _version\n    content\n    createdAt\n    id\n    parentId\n    updatedAt\n  }\n}\n",
	"variables": {
		"input": {
			"id": "4fd52932-3155-4c9f-ab85-99d09cb07a15",
			"content": "Test model android",
			"parentId": null
		}
	}
}
```

GraphQL response
```json
{
	"data": {
		"createTestModel": null
	},
	"errors": [{
		"path": ["createTestModel"],
		"data": null,
		"errorType": "DynamoDB:DynamoDbException",
		"errorInfo": null,
		"locations": [{
			"line": 2,
			"column": 3,
			"sourceName": null
		}],
		"message": "One or more parameter values were invalid: Type mismatch for Index Key parentId Expected: S Actual: NULL IndexName: parent-id-index (Service: DynamoDb, Status Code: 400, Request ID: IPMNR8S6RH0PFO1K81315TBU0JVV4KQNSO5AEMVJF66Q9ASUAAJG, Extended Request ID: null)"
	}]
}
```

amplify-android was silent about this error. (please refer pasted logs above)

After removing `parentId: null` from `variables` listed in the GraphQL request, the model can be saved into DynamoDB.

**Comment by HuiSF** [comment]
The same issue follow up discussed in amplify-ios which possibly applicable here as well:
https://github.com/aws-amplify/amplify-ios/issues/1390#issuecomment-909627296

**Comment by HuiSF** [comment]
This is no longer an issue with GraphQL Transformer v2
example schema
```graphql
type SecondIndexModel @model {
  id: ID! @primaryKey
  parentID: ID @index(name: "parent-id-index")
}
```

**Comment by HuiSF** [comment]
The testing env might have been setup wrongly. This issue is still reproducible with transformer v2

**Comment by HuiSF** [comment]
Amplify CLI opened an issue for looking for a solution https://github.com/aws-amplify/amplify-cli/issues/9915

**Comment by eeatonaws** [comment]
The Amplify CLI issue you linked has been fixed. Are you still observing the issue with the latest versions of Amplify Android and the CLI?

**Comment by shri-onecup** [comment]
@eeatonaws I can confirm it is still happening as of today (Apr-13-2022), at least on Android with the following versions:

CLI: 8.0.1
Amplify Framework: 1.35.0
Kotlin Facade: 0.19.0

**Comment by shri-onecup** [comment]
> Amplify CLI opened an issue for looking for a solution [aws-amplify/amplify-cli#9915](https://github.com/aws-amplify/amplify-cli/issues/9915)

This issue was closed but the problem is still happening on Android. Values are still being set to null and getting rejected by DynamoDB. I tried using AppSync and setting value to null and I can see the exact same error as I see on CloudWatch, which is:

```
"fieldInError": true,
    "errors": [
        "CustomTemplateException(message=One or more parameter values were invalid: Type mismatch for Index Key random_id Expected: S Actual: NULL IndexName: byRandom (Service: DynamoDb, Status Code: 400, Request ID: PMUBED03DU0D4MJLT4L4ODTAJBVV4KQNSO5AEMVJF66Q9ASUAAJG), errorType=DynamoDB:DynamoDbException, data=null, errorInfo=null)"
```

**Comment by HuiSF** [comment]
The underlying issue has been fixed on Amplify CLI side.

Please ensure upgrade to Amplify CLI version >=8.0.2, and re-deploy schema (regenerate resolvers).
