### ISSUE TITLE
Model IDs must be unique in the format of UUID Exception in iOS it's works fine

### ISSUE THREAD

**Issue by maheshordex** [aws-amplify/amplify-android#1500]
### Language and Async Model

Kotlin

### Amplify Categories

DataStore

### Environment information

<details>

```
# Put output below this line
Gradle Version:

gradle-7.0.2-bin.zip


Android Studio Version:

Android Studio Arctic Fox | 2020.3.1 Patch 2
Build #AI-203.7717.56.2031.7678000, built on August 27, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-84-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin
Current Desktop: X-Cinnamon

```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android/

### Describe the bug

I want to sync data to dynamo DB. So I used amplify Datastore to save data.
When I added ID in the model combination of some strings it throws an error.

Android versions:

```
implementation 'com.amplifyframework:core:1.25.0'
implementation 'com.amplifyframework:aws-auth-cognito:1.25.0'
implementation 'com.amplifyframework:aws-datastore:1.25.0'
implementation 'com.amplifyframework:aws-api:1.25.0'

```

Example Model:

```
type UserPreferences @model @auth(rules: [{ allow: owner }]) {
id: ID!
username: String!
name: String!
value: String
}
```

Example Android Code:

```
val ids = "5695542a20f77c4b3364edfcfb9acaf6d92b323c366a7409e8d80f9bcb89ae82My_Test"
val username="+15042010052"
val name="My_Test"
val value="true"
val userPreferences =
            UserPreferences.builder().username(username).name(name).id(ids).value(value).build()

// below code does not execute it throws error above the line.
Amplify.DataStore.save(userPreferences,
{
     debugs(TAG, "Save DataStore Success",item.modelName, it.toJSON())
}, 
{
     errors(TAG, "Save DataStore Error",item.modelName, it)
}
)
```

Error:
```
  java.lang.IllegalArgumentException: Model IDs must be unique in the format of UUID.
        at com.amplifyframework.datastore.generated.model.UserPreferences$Builder.id(UserPreferences.java:228)
```

Line Exception: 228 Check screenshot for it
![Screenshot from 2021-09-17 18-16-44](https://user-images.githubusercontent.com/13220264/133786428-9459661c-25a2-46a0-a8cb-cc820adf0165.png)

**Comment by maheshordex** [comment]
Just FYI I removed the UUID validation code from the Model class but after does this. It throws a warning related to UUID and not saving data.

iOS already developed so it is a big change if it is mandatory to store in UUID format. Even I can't add a new primary key for a workaround solution because iOS have to change a lot for it.

Please need help on it.

**Comment by changxu0306** [comment]
Hello @maheshordex ,
Thanks for reporting the issue. Amplify codegen team already release the PR to fix this problem, see [https://github.com/aws-amplify/amplify-codegen/pull/198](https://github.com/aws-amplify/amplify-codegen/pull/198). Could you please update the Amplify CLI version to the latest, then try to codegen the model again and see how it works?

**Comment by maheshordex** [comment]
@changxu0306 
Do I need to remove the below code manually from each model?
```
try {
            UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
        } catch (Exception exception) {
          throw new IllegalArgumentException("Model IDs must be unique in the format of UUID.",
                    exception);
        }
```

**Comment by maheshordex** [comment]
@changxu0306 
I updated version to 5.6.0 for amplify cli

**Comment by changxu0306** [comment]
> @changxu0306
> Do I need to remove the below code manually from each model?
> 
> ```
> try {
>             UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
>         } catch (Exception exception) {
>           throw new IllegalArgumentException("Model IDs must be unique in the format of UUID.",
>                     exception);
>         }
> ```

You don't need to do anything with the generated model. After upgrading the amplify cli version, run `amplify codegen models` in command line and these code will be removed automatically.

**Comment by maheshordex** [comment]
@changxu0306 
Still, that code exists in models.

```
hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify -v
5.6.0
hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify upgrade
This is the latest Amplify CLI version.
hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify -v
5.6.0
hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify codegen models

GraphQL schema compiled successfully.

Edit your schema at /media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master/amplify/backend/api/amplifysyncdata/schema.graphql or place .graphql files in a directory at /media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master/amplify/backend/api/amplifysyncdata/schema
Successfully generated models. Generated models can be found in /media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master/app/src/main/java
```

```
package com.amplifyframework.datastore.generated.model;

import com.amplifyframework.core.model.temporal.Temporal;

import java.util.List;
import java.util.UUID;
import java.util.Objects;

import androidx.core.util.ObjectsCompat;

import com.amplifyframework.core.model.AuthStrategy;
import com.amplifyframework.core.model.Model;
import com.amplifyframework.core.model.ModelOperation;
import com.amplifyframework.core.model.annotations.AuthRule;
import com.amplifyframework.core.model.annotations.Index;
import com.amplifyframework.core.model.annotations.ModelConfig;
import com.amplifyframework.core.model.annotations.ModelField;
import com.amplifyframework.core.model.query.predicate.QueryField;

import static com.amplifyframework.core.model.query.predicate.QueryField.field;

/** This is an auto generated class representing the UserPreferences type in your schema. */
@SuppressWarnings("all")
@ModelConfig(pluralName = "UserPreferences", authRules = {
  @AuthRule(allow = AuthStrategy.OWNER, ownerField = "owner", identityClaim = "cognito:username", provider = "userPools", operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ })
})
public final class UserPreferences implements Model {
  public static final QueryField ID = field("UserPreferences", "id");
  public static final QueryField USERNAME = field("UserPreferences", "username");
  public static final QueryField NAME = field("UserPreferences", "name");
  public static final QueryField VALUE = field("UserPreferences", "value");
  private final @ModelField(targetType="ID", isRequired = true) String id;
  private final @ModelField(targetType="String", isRequired = true) String username;
  private final @ModelField(targetType="String", isRequired = true) String name;
  private final @ModelField(targetType="String") String value;
  private @ModelField(targetType="AWSDateTime", isReadOnly = true) Temporal.DateTime createdAt;
  private @ModelField(targetType="AWSDateTime", isReadOnly = true) Temporal.DateTime updatedAt;
  public String getId() {
      return id;
  }
  
  public String getUsername() {
      return username;
  }
  
  public String getName() {
      return name;
  }
  
  public String getValue() {
      return value;
  }
  
  public Temporal.DateTime getCreatedAt() {
      return createdAt;
  }
  
  public Temporal.DateTime getUpdatedAt() {
      return updatedAt;
  }
  
  private UserPreferences(String id, String username, String name, String value) {
    this.id = id;
    this.username = username;
    this.name = name;
    this.value = value;
  }
  
  @Override
   public boolean equals(Object obj) {
      if (this == obj) {
        return true;
      } else if(obj == null || getClass() != obj.getClass()) {
        return false;
      } else {
      UserPreferences userPreferences = (UserPreferences) obj;
      return ObjectsCompat.equals(getId(), userPreferences.getId()) &&
              ObjectsCompat.equals(getUsername(), userPreferences.getUsername()) &&
              ObjectsCompat.equals(getName(), userPreferences.getName()) &&
              ObjectsCompat.equals(getValue(), userPreferences.getValue()) &&
              ObjectsCompat.equals(getCreatedAt(), userPreferences.getCreatedAt()) &&
              ObjectsCompat.equals(getUpdatedAt(), userPreferences.getUpdatedAt());
      }
  }
  
  @Override
   public int hashCode() {
    return new StringBuilder()
      .append(getId())
      .append(getUsername())
      .append(getName())
      .append(getValue())
      .append(getCreatedAt())
      .append(getUpdatedAt())
      .toString()
      .hashCode();
  }
  
  @Override
   public String toString() {
    return new StringBuilder()
      .append("UserPreferences {")
      .append("id=" + String.valueOf(getId()) + ", ")
      .append("username=" + String.valueOf(getUsername()) + ", ")
      .append("name=" + String.valueOf(getName()) + ", ")
      .append("value=" + String.valueOf(getValue()) + ", ")
      .append("createdAt=" + String.valueOf(getCreatedAt()) + ", ")
      .append("updatedAt=" + String.valueOf(getUpdatedAt()))
      .append("}")
      .toString();
  }
  
  public static UsernameStep builder() {
      return new Builder();
  }
  
  /** 
   * WARNING: This method should not be used to build an instance of this object for a CREATE mutation.
   * This is a convenience method to return an instance of the object with only its ID populated
   * to be used in the context of a parameter in a delete mutation or referencing a foreign key
   * in a relationship.
   * @param id the id of the existing item this instance will represent
   * @return an instance of this model with only ID populated
   * @throws IllegalArgumentException Checks that ID is in the proper format
   */
  public static UserPreferences justId(String id) {
    try {
      UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
    } catch (Exception exception) {
      throw new IllegalArgumentException(
              "Model IDs must be unique in the format of UUID. This method is for creating instances " +
              "of an existing object with only its ID field for sending as a mutation parameter. When " +
              "creating a new object, use the standard builder method and leave the ID field blank."
      );
    }
    return new UserPreferences(
      id,
      null,
      null,
      null
    );
  }
  
  public CopyOfBuilder copyOfBuilder() {
    return new CopyOfBuilder(id,
      username,
      name,
      value);
  }
  public interface UsernameStep {
    NameStep username(String username);
  }
  

  public interface NameStep {
    BuildStep name(String name);
  }
  

  public interface BuildStep {
    UserPreferences build();
    BuildStep id(String id) throws IllegalArgumentException;
    BuildStep value(String value);
  }
  

  public static class Builder implements UsernameStep, NameStep, BuildStep {
    private String id;
    private String username;
    private String name;
    private String value;
    @Override
     public UserPreferences build() {
        String id = this.id != null ? this.id : UUID.randomUUID().toString();
        
        return new UserPreferences(
          id,
          username,
          name,
          value);
    }
    
    @Override
     public NameStep username(String username) {
        Objects.requireNonNull(username);
        this.username = username;
        return this;
    }
    
    @Override
     public BuildStep name(String name) {
        Objects.requireNonNull(name);
        this.name = name;
        return this;
    }
    
    @Override
     public BuildStep value(String value) {
        this.value = value;
        return this;
    }
    
    /** 
     * WARNING: Do not set ID when creating a new object. Leave this blank and one will be auto generated for you.
     * This should only be set when referring to an already existing object.
     * @param id id
     * @return Current Builder instance, for fluent method chaining
     * @throws IllegalArgumentException Checks that ID is in the proper format
     */
    public BuildStep id(String id) throws IllegalArgumentException {
        this.id = id;
        
        try {
            UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
        } catch (Exception exception) {
          throw new IllegalArgumentException("Model IDs must be unique in the format of UUID.",
                    exception);
        }
        
        return this;
    }
  }
  

  public final class CopyOfBuilder extends Builder {
    private CopyOfBuilder(String id, String username, String name, String value) {
      super.id(id);
      super.username(username)
        .name(name)
        .value(value);
    }
    
    @Override
     public CopyOfBuilder username(String username) {
      return (CopyOfBuilder) super.username(username);
    }
    
    @Override
     public CopyOfBuilder name(String name) {
      return (CopyOfBuilder) super.name(name);
    }
    
    @Override
     public CopyOfBuilder value(String value) {
      return (CopyOfBuilder) super.value(value);
    }
  }
  
}
```

**Comment by changxu0306** [comment]
> @changxu0306
> Still, that code exists in models.
> 
> ```
> hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify -v
> 5.6.0
> hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify upgrade
> This is the latest Amplify CLI version.
> hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify -v
> 5.6.0
> hp@hp:/media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master$ amplify codegen models
> 
> GraphQL schema compiled successfully.
> 
> Edit your schema at /media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master/amplify/backend/api/amplifysyncdata/schema.graphql or place .graphql files in a directory at /media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master/amplify/backend/api/amplifysyncdata/schema
> Successfully generated models. Generated models can be found in /media/hp/D/Mahesh/Nudge/Git/Nudge_Dev/nudge_master/app/src/main/java
> ```
> 
> ```
> package com.amplifyframework.datastore.generated.model;
> 
> import com.amplifyframework.core.model.temporal.Temporal;
> 
> import java.util.List;
> import java.util.UUID;
> import java.util.Objects;
> 
> import androidx.core.util.ObjectsCompat;
> 
> import com.amplifyframework.core.model.AuthStrategy;
> import com.amplifyframework.core.model.Model;
> import com.amplifyframework.core.model.ModelOperation;
> import com.amplifyframework.core.model.annotations.AuthRule;
> import com.amplifyframework.core.model.annotations.Index;
> import com.amplifyframework.core.model.annotations.ModelConfig;
> import com.amplifyframework.core.model.annotations.ModelField;
> import com.amplifyframework.core.model.query.predicate.QueryField;
> 
> import static com.amplifyframework.core.model.query.predicate.QueryField.field;
> 
> /** This is an auto generated class representing the UserPreferences type in your schema. */
> @SuppressWarnings("all")
> @ModelConfig(pluralName = "UserPreferences", authRules = {
>   @AuthRule(allow = AuthStrategy.OWNER, ownerField = "owner", identityClaim = "cognito:username", provider = "userPools", operations = { ModelOperation.CREATE, ModelOperation.UPDATE, ModelOperation.DELETE, ModelOperation.READ })
> })
> public final class UserPreferences implements Model {
>   public static final QueryField ID = field("UserPreferences", "id");
>   public static final QueryField USERNAME = field("UserPreferences", "username");
>   public static final QueryField NAME = field("UserPreferences", "name");
>   public static final QueryField VALUE = field("UserPreferences", "value");
>   private final @ModelField(targetType="ID", isRequired = true) String id;
>   private final @ModelField(targetType="String", isRequired = true) String username;
>   private final @ModelField(targetType="String", isRequired = true) String name;
>   private final @ModelField(targetType="String") String value;
>   private @ModelField(targetType="AWSDateTime", isReadOnly = true) Temporal.DateTime createdAt;
>   private @ModelField(targetType="AWSDateTime", isReadOnly = true) Temporal.DateTime updatedAt;
>   public String getId() {
>       return id;
>   }
>   
>   public String getUsername() {
>       return username;
>   }
>   
>   public String getName() {
>       return name;
>   }
>   
>   public String getValue() {
>       return value;
>   }
>   
>   public Temporal.DateTime getCreatedAt() {
>       return createdAt;
>   }
>   
>   public Temporal.DateTime getUpdatedAt() {
>       return updatedAt;
>   }
>   
>   private UserPreferences(String id, String username, String name, String value) {
>     this.id = id;
>     this.username = username;
>     this.name = name;
>     this.value = value;
>   }
>   
>   @Override
>    public boolean equals(Object obj) {
>       if (this == obj) {
>         return true;
>       } else if(obj == null || getClass() != obj.getClass()) {
>         return false;
>       } else {
>       UserPreferences userPreferences = (UserPreferences) obj;
>       return ObjectsCompat.equals(getId(), userPreferences.getId()) &&
>               ObjectsCompat.equals(getUsername(), userPreferences.getUsername()) &&
>               ObjectsCompat.equals(getName(), userPreferences.getName()) &&
>               ObjectsCompat.equals(getValue(), userPreferences.getValue()) &&
>               ObjectsCompat.equals(getCreatedAt(), userPreferences.getCreatedAt()) &&
>               ObjectsCompat.equals(getUpdatedAt(), userPreferences.getUpdatedAt());
>       }
>   }
>   
>   @Override
>    public int hashCode() {
>     return new StringBuilder()
>       .append(getId())
>       .append(getUsername())
>       .append(getName())
>       .append(getValue())
>       .append(getCreatedAt())
>       .append(getUpdatedAt())
>       .toString()
>       .hashCode();
>   }
>   
>   @Override
>    public String toString() {
>     return new StringBuilder()
>       .append("UserPreferences {")
>       .append("id=" + String.valueOf(getId()) + ", ")
>       .append("username=" + String.valueOf(getUsername()) + ", ")
>       .append("name=" + String.valueOf(getName()) + ", ")
>       .append("value=" + String.valueOf(getValue()) + ", ")
>       .append("createdAt=" + String.valueOf(getCreatedAt()) + ", ")
>       .append("updatedAt=" + String.valueOf(getUpdatedAt()))
>       .append("}")
>       .toString();
>   }
>   
>   public static UsernameStep builder() {
>       return new Builder();
>   }
>   
>   /** 
>    * WARNING: This method should not be used to build an instance of this object for a CREATE mutation.
>    * This is a convenience method to return an instance of the object with only its ID populated
>    * to be used in the context of a parameter in a delete mutation or referencing a foreign key
>    * in a relationship.
>    * @param id the id of the existing item this instance will represent
>    * @return an instance of this model with only ID populated
>    * @throws IllegalArgumentException Checks that ID is in the proper format
>    */
>   public static UserPreferences justId(String id) {
>     try {
>       UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
>     } catch (Exception exception) {
>       throw new IllegalArgumentException(
>               "Model IDs must be unique in the format of UUID. This method is for creating instances " +
>               "of an existing object with only its ID field for sending as a mutation parameter. When " +
>               "creating a new object, use the standard builder method and leave the ID field blank."
>       );
>     }
>     return new UserPreferences(
>       id,
>       null,
>       null,
>       null
>     );
>   }
>   
>   public CopyOfBuilder copyOfBuilder() {
>     return new CopyOfBuilder(id,
>       username,
>       name,
>       value);
>   }
>   public interface UsernameStep {
>     NameStep username(String username);
>   }
>   
> 
>   public interface NameStep {
>     BuildStep name(String name);
>   }
>   
> 
>   public interface BuildStep {
>     UserPreferences build();
>     BuildStep id(String id) throws IllegalArgumentException;
>     BuildStep value(String value);
>   }
>   
> 
>   public static class Builder implements UsernameStep, NameStep, BuildStep {
>     private String id;
>     private String username;
>     private String name;
>     private String value;
>     @Override
>      public UserPreferences build() {
>         String id = this.id != null ? this.id : UUID.randomUUID().toString();
>         
>         return new UserPreferences(
>           id,
>           username,
>           name,
>           value);
>     }
>     
>     @Override
>      public NameStep username(String username) {
>         Objects.requireNonNull(username);
>         this.username = username;
>         return this;
>     }
>     
>     @Override
>      public BuildStep name(String name) {
>         Objects.requireNonNull(name);
>         this.name = name;
>         return this;
>     }
>     
>     @Override
>      public BuildStep value(String value) {
>         this.value = value;
>         return this;
>     }
>     
>     /** 
>      * WARNING: Do not set ID when creating a new object. Leave this blank and one will be auto generated for you.
>      * This should only be set when referring to an already existing object.
>      * @param id id
>      * @return Current Builder instance, for fluent method chaining
>      * @throws IllegalArgumentException Checks that ID is in the proper format
>      */
>     public BuildStep id(String id) throws IllegalArgumentException {
>         this.id = id;
>         
>         try {
>             UUID.fromString(id); // Check that ID is in the UUID format - if not an exception is thrown
>         } catch (Exception exception) {
>           throw new IllegalArgumentException("Model IDs must be unique in the format of UUID.",
>                     exception);
>         }
>         
>         return this;
>     }
>   }
>   
> 
>   public final class CopyOfBuilder extends Builder {
>     private CopyOfBuilder(String id, String username, String name, String value) {
>       super.id(id);
>       super.username(username)
>         .name(name)
>         .value(value);
>     }
>     
>     @Override
>      public CopyOfBuilder username(String username) {
>       return (CopyOfBuilder) super.username(username);
>     }
>     
>     @Override
>      public CopyOfBuilder name(String name) {
>       return (CopyOfBuilder) super.name(name);
>     }
>     
>     @Override
>      public CopyOfBuilder value(String value) {
>       return (CopyOfBuilder) super.value(value);
>     }
>   }
>   
> }
> ```

I see. The UUID check still exist in `justId()` method, which prevents you to set a unique ID without UUID format. Is that correct?

**Comment by maheshordex** [comment]
@changxu0306 
It exists in both place `justId()` and `BuildStep()`

**Comment by maheshordex** [comment]
Just FYI even I removed that code manually after upgrade to `amplify/cli and amplify codegen model` 
but after removing that code data is still not updating on dynamoDb

**Comment by changxu0306** [comment]
In my sample app, it doesn't appear in `BuildStep`. Please make sure you do upgrade to the lastest version. Use `amplify -v` to check your amplify cli version. 

It won't work if you remove code manually because `codegen models` will override what you modified.

**Comment by maheshordex** [comment]
hp@hp:/media/hp/D/***/***/Git/***_Dev/***_master$ amplify -v
5.6.0
hp@hp:/media/hp/D/***/***/Git/***_Dev/***_master$ amplify upgrade
This is the latest Amplify CLI version.

**Comment by changxu0306** [comment]
Mine looks like this:
```
    /** 
     * @param id id
     * @return Current Builder instance, for fluent method chaining
     */
    public BuildStep id(String id) {
        this.id = id;
        return this;
    }
```

**Comment by maheshordex** [comment]
I assume If my code will look likes your code but still when I Datastore.save data it not updating on dynamoDB.

Do I miss anything?

**Comment by changxu0306** [comment]
I'll connect with codegen team about this issue and make change on `justId()` to remove UUID check. But this might take some time. Could you please use another workaround if urgent?

You may try to restart the sync engine after you make the change.

**Comment by maheshordex** [comment]
@changxu0306 

Can you help with this?
I think if I fixed this then the manual removal UUID code will work

`DataStoreException{message=Error in saving the model: SyncedProfile[id=76b02dfb847ac0a3f4be7c4ccc9f010a9d7501b175c6e03ee11be09977bb3305], cause=java.lang.UnsupportedOperationException: Attempted to serialize java.lang.Class: com.amplifyframework.datastore.generated.model.SyncedProfile. Forgot to register a type adapter?, recoverySuggestion=See attached exception for details.}`

**Comment by maheshordex** [comment]
@changxu0306 
Check this warning even after i removed code manually.

`Invalid UUID string: 76b02dfb847ac0a3f4be7c4ccc9f010a9d7501b175c6e03ee11be09977bb3305`

```
2021-09-18 01:09:55.666 3245-3312/com.code.nudge W/amplify:aws-datastore: Storage adapter subscription ended in error
    java.lang.IllegalArgumentException: Invalid UUID string: 76b02dfb847ac0a3f4be7c4ccc9f010a9d7501b175c6e03ee11be09977bb3305
        at java.util.UUID.fromString(UUID.java:194)
        at com.amplifyframework.datastore.syncengine.PendingMutation$PersistentRecord$Builder.containedModelId(PendingMutation.java:456)
        at com.amplifyframework.datastore.syncengine.GsonPendingMutationConverter.toRecord(GsonPendingMutationConverter.java:49)
        at com.amplifyframework.datastore.syncengine.PersistentMutationOutbox.lambda$save$3$PersistentMutationOutbox(PersistentMutationOutbox.java:118)
        at com.amplifyframework.datastore.syncengine.PersistentMutationOutbox$$ExternalSyntheticLambda12.subscribe(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:110)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.rxjava3.internal.observers.DisposableLambdaObserver.onNext(DisposableLambdaObserver.java:58)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by maheshordex** [comment]
@changxu0306 
`Check in datastore syncengine package it throws java.lang.IllegalArgumentException`
package = com.amplifyframework.datastore.syncengine
class  = PendingMutation
method = containedModelId
line no = 456

```
 @NonNull
            PersistentRecord.Builder<T> containedModelId(@NonNull String containedModelId) {
                Objects.requireNonNull(containedModelId);
                // This is stored this way for the purpose of validating hte input.
                this.containedModelId = UUID.fromString(containedModelId);
                return this;
            }

```
```
2021-09-20 10:48:57.203 4460-4520/com.code.xxx W/amplify:aws-datastore: Storage adapter subscription ended in error
    java.lang.IllegalArgumentException: Invalid UUID string: 76b02dfb847ac0a3f4be7c4ccc9f010a9d7501b175c6e03ee11be09977bb3305
        at java.util.UUID.fromString(UUID.java:194)
        at com.amplifyframework.datastore.syncengine.PendingMutation$PersistentRecord$Builder.containedModelId(PendingMutation.java:456)
        at com.amplifyframework.datastore.syncengine.GsonPendingMutationConverter.toRecord(GsonPendingMutationConverter.java:49)
        at com.amplifyframework.datastore.syncengine.PersistentMutationOutbox.lambda$save$3$PersistentMutationOutbox(PersistentMutationOutbox.java:118)
        at com.amplifyframework.datastore.syncengine.PersistentMutationOutbox$$ExternalSyntheticLambda12.subscribe(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableCreate.subscribeActual(CompletableCreate.java:40)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:43)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
        at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFlatMapCompletableCompletable$FlatMapCompletableMainObserver.onNext(ObservableFlatMapCompletableCompletable.java:110)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.rxjava3.internal.observers.DisposableLambdaObserver.onNext(DisposableLambdaObserver.java:58)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

```

**Comment by changxu0306** [comment]
The string `76b02dfb847ac0a3f4be7c4ccc9f010a9d7501b175c6e03ee11be09977bb3305` is not in UUID format. So, an `IllegalArgumentException` is thrown by the codegen models. I think the only workaround for you at this moment is to change the id into UUID format. We'll work on the fix on this check immediately. Please stay tuned for the update.

**Comment by jamesonwilliams** [comment]
See also https://github.com/aws-amplify/amplify-android/issues/846

**Comment by gpanshu** [comment]
This has been fixed in the latest codegen models CLI.

**Comment by shri-onecup** [comment]
As of CLI 7.6.23, I am still getting:

```
W/amplify:aws-datastore: Storage adapter subscription ended in error
    java.lang.IllegalArgumentException: Invalid UUID string: 95270001LMXDBPOG
        at java.util.UUID.fromString(UUID.java:194)
```

**Comment by poojamat** [comment]
@shri-onecup sorry to hear that you are still facing the issue. Did you regenerate your models with the new CLI? Please run "npm i -g @aws-amplify/cli ". After that is successful run "amplify codegen models". Choose depth to be 4. After that please confirm that UUID check is removed for the models buildstep id.

**Comment by shri-onecup** [comment]
@poojamat thanks for the reply. I did the following:
1. Run "npm i -g @aws-amplify/cli"
2. "amplify configure codegen" & select depth to be 4
3. "amplify codegen models"
4. Attempt save operation on an object with custom PK. 

Still getting the same error:
`W/amplify:aws-datastore: Storage adapter subscription ended in error
    java.lang.IllegalArgumentException: Invalid UUID string: 1
        at java.util.UUID.fromString(UUID.java:194)`

Here's my code:
##Code
```kotlin
Amplify.DataStore.query(Blog::class, Where.id("1"))
                .catch { Log.e("DataStore", "Query failed") }
                .map { it.copyOfBuilder().name("test_update").build() }
                .onEach { Amplify.DataStore.save(it) }
                .catch { Log.e("DataStore", "Save failed") }
                .collect { Log.d("DataStore", "Updated blog") }
```
## GraphQL Schema

<details>

```graphql
type Blog @model {
    id: ID!
    name: String!
    customs: [MyCustomModel]
    notes: [String]
    post: [Post] @hasMany(indexName: "postByBlog", fields: ["id"])
}

type MyCustomModel {
    id: ID!
    name: String!
    desc: String
    children: [MyNestedModel]
}

type MyNestedModel {
    id: ID!
    nestedName: String!
    notes: [String]
}

type Post @model {
    id:ID!
    name:String!
    blog_id: ID! @index(name: "postByBlog")
    blog: Blog  @belongsTo(fields: ["blog_id"])
}

```

</details>

##Terminal Log

<details>

```

(base) OneCupAI@Shri-MBP DataStoreCRUD % amplify configure codegen
? Choose the AppSync API datastore3
? Enter the file name pattern of graphql queries, mutations and subscriptions app/src/main/graphql/**/*.graphql
? Enter maximum statement depth [increase from default if your schema is deeply nested] 4
Codegen configured. Remember to run "amplify codegen" to generate your types and statements.
(base) OneCupAI@Shri-MBP DataStoreCRUD % amplify codegen
✔ Generated GraphQL operations successfully and saved at app/src/main/graphql/com/amazonaws/amplify/generated/graphql
✔ Generated GraphQL operations successfully and saved at app/src/main/graphql/com/amazonaws/amplify/generated/graphql
(base) OneCupAI@Shri-MBP DataStoreCRUD % amplify codegen models
(node:28510) [DEP0128] DeprecationWarning: Invalid 'main' field in '/opt/homebrew/lib/node_modules/@aws-amplify/cli/node_modules/cloudform/package.json' of 'packages/cloudform/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)

⚠️  WARNING: your GraphQL API currently allows public create, read, update, and delete access to all models via an API Key. To configure PRODUCTION-READY authorization rules, review: https://docs.amplify.aws/cli/graphql/authorization-rules

GraphQL schema compiled successfully.

Edit your schema at /Users/OneCupAI/AndroidStudioProjects/DataStoreCRUD/amplify/backend/api/datastore3/schema.graphql or place .graphql files in a directory at /Users/OneCupAI/AndroidStudioProjects/DataStoreCRUD/amplify/backend/api/datastore3/schema
Successfully generated models. Generated models can be found in /Users/OneCupAI/AndroidStudioProjects/DataStoreCRUD/app/src/main/java

```


</details>
