### ISSUE TITLE
Amplify.Auth.fetchAuthSession() returns the same access token even after expiry

### ISSUE THREAD

**Issue by ionutgh** [aws-amplify/amplify-android#1763]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin - Coroutines

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy


implementation 'com.amplifyframework:core-kotlin:0.19.4'
implementation 'com.amplifyframework:aws-auth-cognito:1.35.5'
```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.2
------------------------------------------------------------

Build time:   2021-08-17 09:59:03 UTC
Revision:     a773786b58bb28710e3dc96c4d1a7063628952ad

Kotlin:       1.5.21
Groovy:       3.0.8
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.6 (AdoptOpenJDK 11.0.6+10)
OS:           Mac OS X 10.16 x86_64



```

</details>

### Describe the bug

I am using Amplify authentication to signup/login and get an authToken that I use to authenticate with our api. Everything works fine until the access token's expiration. After that point every time I try to get a new token (using Amplify.Auth.fetchAuthSession()) I only get the same expired token. I am fetching the auth session on app's start and every time I get a 401 code response from our api, every time the token I receive is the same. The only solution to get a new valid token is to Log out -> Log in -> Amplify.Auth.fetchAuthSession but I don't think that's the intended behaviour.

### Reproduction steps (if applicable)

1. Login using amplify and get the accessToken
2. Wait for the token to expire
3. Try getting a new accessToken by calling Amplify.Auth.fetchAuthSession()
4. Notice that the token I get is the same token as the initial one which expired.

### Code Snippet

```java

override suspend fun getAuthSession(): Outcome<AuthSession> {
        return try {
            val session = Amplify.Auth.fetchAuthSession()
            Log.i("AmplifyQuickstart", "Auth session = $session")
            keyValuePersistentData.setValue(
                TOKEN_KEY,
                (session as AWSCognitoAuthSession).userPoolTokens.value?.accessToken
            )
            Outcome.success(session as AuthSession)
        } catch (e: Exception){
            Outcome.failure(e)
        }

    }
```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### amplifyconfiguration.json

{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-north-1_WzFxOg9l7",
                        "AppClientId": "76c0ocgfjp3jc8mmk6p2ge2c43",
                        "Region": "eu-north-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by sdhuka** [comment]
@ionutgh you could use this [workaround](https://github.com/aws-amplify/aws-sdk-android/issues/696#issuecomment-1101894554) until we have an API to force refresh the token.

**Comment by ionutgh** [comment]
Thank you for your answer @sdhuka .

 It looks like the workaround is not working for me. According to the post it looks like I would just need to call CognitoIdentityProviderClientConfig.setRefreshThreshold just before Amplify.Auth.fetchAuthSession(), with a value that is greater than the token expiration.
 In my case the auth token is set to expire in 5 minutes and I am calling CognitoIdentityProviderClientConfig.setRefreshThreshold(360 * 1000L) - 6 minutes. 5 minutes after the initial login, I still get the old expired token each time I call Amplify.Auth.fetchAuthSession(). Am I missing something?

I also noticed looking at the CognitoIdentityProviderClientConfig.setRefreshThreshold method(code below) that it looks like the parameter can have a maximum value of 1800000, so what would be the solution if the auth token expiration is set to a value greater than 30 minutes?

**Comment by smartpuffindev** [comment]
Hello @sdhuka,

I have exactly the same problem. I also can't make `fetchAuthSession` refresh the id token. This is the [code I run](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/#initialize-amplify-auth) and the exception I get:
```
Amplify.Auth.fetchAuthSession(
    result -> Log.i("AmplifyQuickstart", result.toString()),
    error -> Log.e("AmplifyQuickstart", error.toString())
);
```
```
   com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Invalid login token. Token expired: XXX >= XXX (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: XXX)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        ...
```

The only way I found to make this work is to log out and log in again. As an example, I closed the app for the night and came back in the morning to the same exception.

The solution you link to [here](https://github.com/aws-amplify/aws-sdk-android/issues/696#issuecomment-1101894554) doesn't do anything for me. If I look at the tokens in the callback of `getTokens`, they are still the same, and the exception is still in place, and the token is still expired. Perhaps I didn't set the right value; but I have the same questions about it as @ionutgh in the comment above.

Id token expiration is set to 60 minutes by default and can be raised to maximum of 1 day. This means our users will have to log in every day, which is absolutely unacceptable for us, as I'm sure you understand.

How do we make sure we have valid tokens after the first expiration?

Thank you.

**Comment by gpanshu** [comment]
Hello @smartpuffindev I am looking at the issue and will advise soon. Thank you

**Comment by smartpuffindev** [comment]
Thankss @gpanshu, really appreciate your response. Please let me know if you need more details.

The versions I'm using: 
```
    implementation 'com.amplifyframework:core:1.35.4'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
    implementation 'com.amplifyframework:aws-auth-cognito:1.35.4'
```

Regarding the implementation, I am mostly following [this official guide](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android/).

What worked for me (still in development, I'm somewhat hesitant to use it in production) is this [approach with reflection](https://github.com/aws-amplify/amplify-android/issues/919#issuecomment-917879951). As no hub events happen for me, I'm scheduling this repeatedly on timer set to "ID token expiration - 1 minute".

Thanks!

**Comment by gpanshu** [comment]
The original issue from the @ionutgh is that they get the same token after setting a timeout to 6 minutes which is when their token expiry is. 
From what I understand on your issue you are setting the timeout for 6 minutes and then doing a fetchAuthSession after 5 minutes and you are getting the same token. As mentioned by @sdhuka can you please try to manually refresh the token after 5 minutes using `AWSMobileClient.getInstance().getTokens();` and see if that force refreshes it. 

As for @smartpuffindev problem which is different as you are trying to do a fetchAuthSession when your token is expired. I would recommend to try manually refreshing the token before expiry time of your token to see if that works?

**Comment by smartpuffindev** [comment]
Sorry if I piggy backed on the wrong issue! I was under the impression I have the same problem; sorry if I misunderstood or mis-explained it.

> The original issue from the @ionutgh is that they get the same token after setting a timeout to 6 minutes which is when their token expiry is.
Yes, this is the same problem I am experiencing as well. Let me try to clarify it step by step. Let us say I'm not employing the reflection-on-timer trick.

I'm following the tutorial, in the onCreate method of my activity I'm setting up the hub as recommended [here](https://docs.amplify.aws/lib/auth/auth-events/q/platform/android/). After that I'm calling `Amplify.Auth.fetchAuthSession`. I also have a "log in" button that sends the user to the web ui. I also set the id token expiry to 5 minutes for testing purposes.

The user opens the app. `fetchAuthSession` prints:

```AWSCognitoAuthSession{isSignedIn=false, awsCredentials=..... error=SignedOutException{message=You are currently signed out., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}```

The user logs in. If I call `fetchAuthSession` now, it says:

```AWSCognitoAuthSession{isSignedIn=true,... userPoolTokens='AuthSessionResult{value=AWSCognitoUserPoolTokens{accessToken=XXXX, idToken=YYYY...```

I can also print the id token from `AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString()`, it also prints YYYY.
I also fetch [user attributes](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/android/) at this moment and get the user's email.

I call my own API and pass the id token (I print it, it shows YYYY). All is well.

---

5 minutes pass. The next call to my own API with the id token returns 401 Unauthorised.

---

From this moment on, I'm stuck. If I'm calling `AWSMobileClient.getInstance().getTokens()`, the token is YYYY (the old one). If I restart the app, the token is still YYYY.

If I call `fetchAuthSession`, I see: 

```AWSCognitoAuthSession{isSignedIn=true, ...userPoolTokens='AuthSessionResult{value=null, error=SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}, type=FAILURE}'}```

(As a side note, isn't it weird that it says `isSignedIn=true, please sign in`?)

---

The [solution](https://github.com/aws-amplify/aws-sdk-android/issues/696#issuecomment-1101894554) (setRefreshThreshold && AWSMobileClient.getInstance().getTokens()) that you mention doesn't work for me, the token I print from `getTokens()` is still YYYY. I didn't quite understand what threshold value should be the proper one - please see questions above - but I've tried it with different values, and the token is still the same before or after the set threshold.

If the user logs out and logs in, the id token is now YYYZ, and everything works again.

I hope this is more clear. Again, sorry if this is the wrong issue, but I'm still under the impression that we experience the same problem.

**Comment by ionutgh** [comment]
@gpanshu 

Thank you for the reply, indeed I don't think @smartpuffindev 's issue is exactly the same as mine. Just for a quick recap, my issue is the following:

Login to amplify
After the access token expires (we have the expiration set to 5 minutes for dev purposes but I'm not sure this is relevant), if I call fetchAuthSession, I still get the old access token (which is expired). - I do not get any error like the one @smartpuffindev posted above.
Calling AWSMobileClient.getInstance().getTokens() gets me the exact same tokens as calling fetchAuthSession.

It was suggested above to call setRefreshThreshold with a value greater than the token expiry value (in my case the token expiry is set to 5 minutes so I am calling setRefreshThreshold with a value of 6 minutes). This doesn't work and even if it did, if you call setRefreshThreshold with a value greater that 30 minutes it will throw an exception - we will probably have a token expiry greater than 30 minutes in production.

Another weird thing is that this is not happening all the time, for example last week everything worked fine from wed to Friday (fetchAuthSession returned valid tokens). Today the issue is happening. The code is absolutely the same.

**Comment by gpanshu** [comment]
That is actually strange. I tested that yesterday and I did get the session expired error upon expiry of the token. 
I was only able to put the refreshToken to 60 minutes as that is the min on our end through the app config in AWS. Perhaps try with a longer interval like 60 minutes and let's ignore the setRefreshThreshold for now as that does not seem to work for you.

How many users of yours does this affect and can you give me any more context or logs around when this happens in production?

**Comment by ionutgh** [comment]
@gpanshu We are not yet in production there are 2 android developers on the team and the issue happens to both of us I think we both tried creating 2 accounts and it happened for all of them. 

I also created a new android project(using the same config json) that has only one button and 2 textviews. Tapping the button will either login or fetch a new token, here's the code below: 

`val session = Amplify.Auth.fetchAuthSession()
            if(!session.isSignedIn) {
                Amplify.Auth.signIn("alex@nakko.com", "Pass1234#")
                login()
            } else {
                if(oldToken != (session as AWSCognitoAuthSession).userPoolTokens.value?.accessToken) {
                    findViewById<TextView>(R.id.isNew).text = "NEW TOKEN!!!"
                    sp.edit().putString("OLDTOKEN", (session as AWSCognitoAuthSession).userPoolTokens.value?.accessToken).apply()
                } else {
                    findViewById<TextView>(R.id.isNew).text = "SAME OLD TOKEN!!!"
                }
                findViewById<TextView>(R.id.lastToken).text = (session as AWSCognitoAuthSession).userPoolTokens.value?.accessToken
            }`

Tapping the button always gets the same old token even long after the 5 minutes pass and the access token expire. I see no errors or exceptions, this is the log output when I press the button and fetchAuthSession is being called: 

2022-06-11 17:58:23.210 5383-5550/com.example.amplifytest D/AWSMobileClient: Inspecting user state details
2022-06-11 17:58:23.243 5383-5550/com.example.amplifytest D/AWSMobileClient: hasFederatedToken: false provider: cognito-idp.eu-north-1.amazonaws.com/eu-north-1_WzFxOg9l7

**Comment by MarlonJD** [comment]
My test values are 30 days, 5min, 5min still having same issue. after 5 minutes it cannot refresh and gives me: (message: Session expired could not fetch user sub, recoverySuggestion: Invoke Auth.signIn to re-authenticate the user. Need to handle this huge issue asap

**Comment by MarlonJD** [comment]
![image](https://user-images.githubusercontent.com/8514643/174110786-e2840853-333f-490b-a2cc-3bc181107829.png)

Here's the my settings. I'm using flutter btw but there's directly using here amplify-android with method channel. I tested on iOS it gives me error and also android gives me error:

```
E/amplify:flutter:auth_cognito(27962): SessionExpiredException
E/amplify:flutter:auth_cognito(27962): SessionExpiredException{message=Your session has expired., cause=null, recoverySuggestion=Please sign in and reattempt the operation.}
E/amplify:flutter:auth_cognito(27962): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.prepareCognitoSessionFailure(AuthCognito.kt:633)
E/amplify:flutter:auth_cognito(27962): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.onFetchAuthSession$lambda-18(AuthCognito.kt:387)
E/amplify:flutter:auth_cognito(27962): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito.$r8$lambda$uu-F3NQTLN2zVTYaQlc45ppd10Q(AuthCognito.kt)
E/amplify:flutter:auth_cognito(27962): 	at com.amazonaws.amplify.amplify_auth_cognito.AuthCognito$$ExternalSyntheticLambda30.accept(D8$$SyntheticClass)
E/amplify:flutter:auth_cognito(27962): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$7.onResult(AWSCognitoAuthPlugin.java:578)
E/amplify:flutter:auth_cognito(27962): 	at com.amplifyframework.auth.cognito.AWSCognitoAuthPlugin$7.onResult(AWSCognitoAuthPlugin.java:568)
E/amplify:flutter:auth_cognito(27962): 	at com.amazonaws.mobile.client.internal.ReturningRunnable$1.run(ReturningRunnable.java:44)
E/amplify:flutter:auth_cognito(27962): 	at java.lang.Thread.run(Thread.java:761)
I/flutter (27962): Error when tring to refresh: SessionExpiredException(message: Your session has expired., recoverySuggestion: Please sign in and reattempt the operation., underlyingException: null)
```

**Comment by MarlonJD** [comment]
OK, I succeed.
I did 30 days, 7min, 7min (Someone said you should minimum 7minutes for some reason, don't remember where it is)
![image](https://user-images.githubusercontent.com/8514643/174118074-8c6a20a7-de12-42dd-be2c-192a6a77b6b6.png).
And disable remember me on user pool. (User pool -> Devices)
![image](https://user-images.githubusercontent.com/8514643/174118265-28212074-da95-4343-ae7f-14516c6fa908.png)
 and it works on ios and android. yaay!

**Comment by gpanshu** [comment]
If you can connect with us on Discord, we can setup a call to help troubleshoot.

**Comment by gpanshu** [comment]
Thank you for providing this workaround. I will check within our system to understand why that might be the case. I am closing this as resolved for now.

**Comment by ionutgh** [comment]
@gpanshu I will check to see if this works, if it still happens I will reopen the issue

**Comment by MarlonJD** [comment]
> @gpanshu I will check to see if this works, if it still happens I will reopen the issue

Yes please try i tried and it works for me. BTW it's a bug. Why remember device (track device) blocking refreshing token. İ think this should be issue should be fixed

**Comment by MarlonJD** [comment]
I'd you try same account. İt's not works. Please sign out first then signIn again wait 7 minutes (settings on user pool client) and see if it's works

**Comment by ionutgh** [comment]
right now, today it is working with 5 minutes without changing anything since yesterday

**Comment by MarlonJD** [comment]
@ionutgh so your issue also fixed now ?

**Comment by ionutgh** [comment]
@gpanshu The issue is not fixed. It worked well on Friday but today I still get the expired token. I have the app installed on 2 physical phones and 1 emulator (diff accounts) on one device the token still gets refreshed, on the other device and on emulator I keep getting the same expired token.

**Comment by ranshine** [comment]
I am facing same issue, getting same id token even though it is expired, is this issue resolved ?

**Comment by ranshine** [comment]
I am facing same issue, getting same id token even though it is expired, is this issue resolved ?

**Comment by gpanshu** [comment]
Hi @ranshine have you tried using V2.0 of Amplify Android library ? We have completely rewritten it in Kotlin and addressed a lot of technical debt. If upgrading it is an option I would ask that you upgrade your library to the latest and give it a try to see if your issue is fixed. In the meantime I will re-open this issue and await your answer.

**Comment by ionutgh** [comment]
@ranshine Hi, this issue is no longer happening for me on any android device. It is still happening sometime tho if using the emulator.

**Comment by gpanshu** [comment]
@ionutgh are you using v2 or v1 ?

**Comment by gpanshu** [comment]
Closing due to inactivity. I would also recommend that you update to V2 if you have not already and if upgrading is an option for you.

**Comment by etisamzafarswipbox** [comment]
Amplify.Auth.fetchAuthSession(
            {
                val session = it as AWSCognitoAuthSession
                when (session.identityIdResult.type) {
                    AuthSessionResult.Type.SUCCESS ->{
                        Log.i(TAG, "Identity Id = ${session.identityIdResult.value}")
                        Log.i(TAG, "session state signed in = ${session.isSignedIn}")
                        if(session.isSignedIn){
                            try {
                             

                            }
                            catch (e: Exception){

                            }

                        }
                    }
                    AuthSessionResult.Type.FAILURE ->{
                        Log.w("AuthQuickStart", "IdentityId not found", session.identityIdResult.error)
                    }
                }
            },
            { Log.e("AuthQuickStart", "Failed to fetch session", it) }
        )

**Comment by MarlonJD** [comment]
> Amplify.Auth.fetchAuthSession( { val session = it as AWSCognitoAuthSession when (session.identityIdResult.type) { AuthSessionResult.Type.SUCCESS ->{ Log.i(TAG, "Identity Id = ${session.identityIdResult.value}") Log.i(TAG, "session state signed in = ${session.isSignedIn}") if(session.isSignedIn){ try {
> 
> ```
>                         }
>                         catch (e: Exception){
> 
>                         }
> 
>                     }
>                 }
>                 AuthSessionResult.Type.FAILURE ->{
>                     Log.w("AuthQuickStart", "IdentityId not found", session.identityIdResult.error)
>                 }
>             }
>         },
>         { Log.e("AuthQuickStart", "Failed to fetch session", it) }
>     )
> ```

Go to cognate console on aws,
Amazon Cognito -> User pools -> your pool -> Sign-in experience (on the tab) -> Device tracking (At the bottom)
What is the answer of Remember user devices? If it's on try to off it to _Don't remember_

**Comment by buntupana** [comment]
This issue is still happening to me in V2. I can't find a way to get it work other than sing-out and sing-in again

**Comment by ranshine** [comment]
@ionutgh, I am using com.amplifyframework:aws-auth-cognito:1.37.11, still see expired token in android emulator. Should i use latest Amplify Android 1.38.1.

**Comment by StefanoStream** [comment]
We are facing the same issue in V2 using the latest library at the moment:
```
    implementation 'com.amplifyframework:core:2.13.2'
    implementation 'com.amplifyframework:aws-api:2.13.2'
    implementation 'com.amplifyframework:aws-auth-cognito:2.13.2'
```
We tried to change backend values like [here](https://github.com/aws-amplify/amplify-android/issues/1763#issuecomment-1157867774) but still returns an expired token after 7 minutes.
We also tried to add the `forceRefresh` option when invoke the `fetchAuthSession` in this way:
```
val option = AuthFetchSessionOptions.builder().forceRefresh(true).build()
Amplify.Auth.fetchAuthSession(option,
...
```
Same result. We are planning to release in production but we need to fix this issue first. 
Can someone help up to resolve this token issue, please? @gpanshu 
Thanks!

**Comment by tylerjroach** [comment]
@StefanoStream Please open a new issue with your specific information. Ex: Amplify configuration file, Cognito refresh settings, sign in method used (SRP, web, etc).
