### ISSUE TITLE
A notification appears on user devices

### ISSUE THREAD

**Issue by yaroslav-v** [aws-amplify/amplify-android#1803]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Java

### Amplify Categories

Authentication, Storage

### Gradle script dependencies

<details>

```groovy
implementation "com.amplifyframework:core:1.35.6"
implementation "com.amplifyframework:aws-storage-s3:1.35.6"
implementation "com.amplifyframework:aws-auth-cognito:1.35.6"


```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.0.2
------------------------------------------------------------

Build time:   2021-05-14 12:02:31 UTC
Revision:     1ef1b260d39daacbf9357f9d8594a8a743e2152e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_301 (Oracle Corporation 25.301-b09)
OS:           Mac OS X 10.16 x86_64


```

</details>

### Describe the bug

Hi!

After updating to the library v1.35.6, users have started seeing a new notification in the status bar with the text "Amplify transfer service is running".

As far as I understand, it was implemented intentionally according to this conversation https://github.com/aws-amplify/amplify-android/pull/1759

Is there a way to hide this notification? Our app doesn't need it because it has its own foreground service etc. and the users are a bit annoyed by another dummy notification 🤷‍♂️

### Reproduction steps (if applicable)

Use amplifyframework v1.35.6

### Code Snippet

```java
// Initialization in Application class

LogFactory.setLevel(LogFactory.Level.OFF);

Amplify.addPlugin(new AWSCognitoAuthPlugin());
Amplify.addPlugin(new AWSS3StoragePlugin());

AmplifyConfiguration amplifyConfig = AmplifyConfiguration.builder(context)
		.devMenuEnabled(false)
		.build();
Amplify.configure(amplifyConfig, context);



// Uploading, somewhere in the app

DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ", Locale.US);
dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));

Map<String, String> metadata = new ArrayMap<>(4);
metadata.put("date", dateFormat.format(date));
metadata.put("token", authToken);

StorageUploadFileOptions options =
		StorageUploadFileOptions.builder()
				.accessLevel(StorageAccessLevel.PUBLIC)
				.contentType(mimeType)
				.metadata(metadata)
				.build();

Amplify.Storage.uploadFile(
		"gl_" + new Date().getTime() + "_" + fileName,
		file,
		options,
		result -> {
			// write success logs
		},
		failure -> {
			// write failure logs
		}
);

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Hi @yaroslav-v,

While the transfer is running, we intend to display the foreground service notification to ensure that the transfer continues if the app is backgrounded/killed. Ideally, this foreground notification should only show while transfer(s) are in progress.

However, I have observed that even after a transfer completes, the notification continues to display, even if the app itself is killed. This appears to be a bug that our TransferService is not being stopped upon all transfers completing.

As a workaround, you can stop the service manually, which will remove the notification. This could be called inside a transfer's onSuccess callback (if there are no other transfers currently running):
```
stopService(Intent(context, TransferService::class.java))
```

**Comment by yaroslav-v** [comment]
Thx!

**Comment by tylerjroach** [comment]
I do not have an ETA to provide, but can you explain scenarios where the workaround is not sufficient? We can take a further look in those areas.

**Comment by yaroslav-v** [comment]
@tylerjroach As far as I understand, this is due to our corner case with an already existing foreground notification.

If we try to send something to AWS, the SDK pushes a new foreground notification and, because there couldn't be 2 simultaneous foreground notifications, the AWS notification interchanges ours and it hangs there even after the AWS service shuts down.

**Comment by tylerjroach** [comment]
@yaroslav-v, I believe 2 simultaneous foreground services shouldn't be a problem. It appears that our notification id being used is `1`. Is it possible your own foreground service notification is starting with this same id? This would cause the overwrites. We will look into changing our default notification id to something that will be less likely to conflict.

**Comment by tylerjroach** [comment]
@srajendiran30, the workarounds described in this issue should work until a more permanent fix is released.

**Comment by srajendiran30** [comment]
I tried stopped services and cancel async tasks but did not help.Even after app is closed the notification is still hanging

**Comment by srajendiran30** [comment]
Can you escalate marking it as a priority? Because  wont be able to ship the application because of this issue. please.

**Comment by srajendiran30** [comment]
Any idea when will this be fixed?

**Comment by srajendiran30** [comment]
![WhatsApp Image 2022-07-19 at 5 22 35 PM](https://user-images.githubusercontent.com/48789233/179744006-ff59a428-9cce-4051-b42b-8f177cf542aa.jpeg)
 
Screenshot for your reference

**Comment by srajendiran30** [comment]
![WhatsApp Image 2022-07-19 at 5 22 35 PM](https://user-images.githubusercontent.com/48789233/179744579-0fd521a6-62e8-4df6-a143-0ebce74013b5.jpeg)
Screenshot for your reference

**Comment by tylerjroach** [comment]
@srajendiran30 I've attached draft PRs of the fix. I will remove the draft labels once I have had enough time to test. In the meantime, could you post the code you have used to try and dismiss the notification? Any call to `context.stopService(new Intent(context, TransferService.class));` should immediately dismiss the notification.

**Comment by srajendiran30** [comment]
> @srajendiran30 I've attached draft PRs of the fix. I will remove the draft labels once I have had enough time to test. In the meantime, could you post the code you have used to try and dismiss the notification? Any call to `context.stopService(new Intent(context, TransferService.class));` should immediately dismiss the notification.

@tylerjroach I tried the same from your recommendation from above but it did not work out. I  also tried to stop the ASync task which is used to invoke the process. But did not worked out. Finally I am doing brute force by killing the process using `android.os.Process.killProcess`  which is not good for the overall health of the application. Anyways I hope that you will approve the changes soon and the notification will be completely removed,(Not partially)

**Comment by tylerjroach** [comment]
Improvements have been merged into main to dismiss the notification when transfers have completed. Will take a look at updating the notification text to be more generic before this goes into release.

**Comment by srajendiran30** [comment]
Thats a great work @tylerjroach !Kudos for your efforts. But if there is a possibility to completely get rid of the notification it would be great! Because I feel by letting the notification the security of the application is compromised to some degree. You can conduct customer research and determine what others say. But it is a desirable feature from my end. Thank you for understanding, Thanks again.

**Comment by tylerjroach** [comment]
Amplify Android 1.36.4 has been released with the fix.

@srajendiran30 I understand the ask to not show a notification. We will discuss this more internally, to see what our options are on when to display (or not to display) the notification, as well as how to allow developers to customize the notification better. 

Due to the way Android background processing works, foreground notifications are currently necessary to guarantee large transfers do not get killed (or cause a crash) when the application goes to the background. On Android 12+, the notification will only show if transfers are in progress for > 10 seconds (see: https://developer.android.com/guide/components/foreground-services).

Additionally, I can assure you that there are no security concerns caused by the app displaying a foreground notification.

I am going to go ahead and close this issue since the reported bug has been released.

**Comment by djsjr** [comment]
@tylerjroach Wow. I can't initiate any a transfer without a notification showing up now? If it IS necessary under specific circumstances due to the constraints given by Android, fine.

But as of now, I can't ship my app with this. It's completely unprofessional.

Frankly, I find it a bit absurd that this was implemented before refining and really narrowing down when this has to be displayed and what type of customization can occur.

**Comment by tracedmark** [comment]
@tylerjroach How are those discussions going?

We didn't know about this change and now the app is live with the notifications popping up and customers are querying what it is and they don't like it. It looks suspicious, no normal user would have a clue what 'Amplify' is. 

Ideally there would be no notification at all. If there has to be, we need to be able to customise this so it looks professional and part of our app asap please.

**Comment by tylerjroach** [comment]
@tracedmark Please update to the latest version of Amplify. 'Amplify' is no longer mentioned in the notification, instead showing 'File transfer in progress'. The notification also only displays while a transfer is in progress. Please see here: https://github.com/aws-amplify/amplify-android/issues/1887#issuecomment-1218367993 for a possible workaround to remove the notification until further changes are made on our end to either remove the notification entirely, or provide a customization option on when to display.
