### ISSUE TITLE
CodeValidationException when calling signInWithWebUI

### ISSUE THREAD

**Issue by moamenet** [aws-amplify/amplify-android#2238]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-android/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-android/discussions).

### Language and Async Model

Kotlin

### Amplify Categories

Authentication

### Gradle script dependencies

<details>

```groovy
implementation 'com.amplifyframework:core:2.1.0'
implementation 'com.amplifyframework:aws-auth-cognito:2.1.0'
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

```

</details>

### Environment information

<details>

```
------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18 (Homebrew 18+0)
OS:           Mac OS X 13.1 aarch64


```

</details>

### Please include any relevant guides or documentation you're referencing

https://docs.amplify.aws/lib/auth/signin/q/platform/android/

### Describe the bug

I am trying to upgrade my project from amplify 1 to amplify 2. The project is already live running on version 1, so my config files should be correct, at least for version 1.
After upgrading to version 2, I am not able to sign in anymore with web UI, when the function is called, the browser tab opens and immediately closes again with a CodeValidationException:

I also tried starting a fresh new project from scratch, following the documentation, but with the same result.
I am not using amplify (or the cli), but a Cognito User Pool without an Identity Pool.

### Code Snippet

```java
override fun onCreate(savedInstanceState: Bundle?) {
    binding.fab.setOnClickListener {view ->
          Amplify.Auth.signInWithWebUI(
              this,
              { Log.i("MyAmplifyApp", "Signin OK = $it") },
              { Log.e("MyAmplifyApp", "Signin failed", it) }
          )
      }

      try {
          Amplify.addPlugin(AndroidLoggingPlugin(LogLevel.VERBOSE))
          Amplify.addPlugin(AWSCognitoAuthPlugin())
          Amplify.configure(applicationContext)
          Log.i("MyAmplifyApp", "Initialized Amplify")
      } catch (error: AmplifyException) {
          Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
      }
  }
``


### Log output

<details>

```
// Put your logs below this line
CodeValidationException{message=invalid_request, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
at com.amplifyframework.auth.cognito.HostedUIClient.fetchToken(HostedUIClient.kt:106)
at com.amplifyframework.auth.cognito.actions.HostedUICognitoActions$fetchHostedUISignInToken$$inlined$invoke$1.execute(Action.kt:73)
at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

</details>


### amplifyconfiguration.json

```json
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "$poolId",
            "AppClientId": "$appClient",
            "Region": "$region"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {
              "WebDomain": "auth.XYZ.com",
              "AppClientId": "$appClient",
              "SignInRedirectURI": "myApp://",
              "SignOutRedirectURI": "myApp://",
              "Scopes": [
                "email",
                "openid",
                "profile",
                "aws.cognito.signin.user.admin"
              ]
            }
          }
        }
      }
    }
  }
}
```

awsconfiguration.json

```json
{
  "IdentityManager": {
    "Default": {}
  },
  "CognitoUserPool": {
    "Default": {
      "AppClientId": "$appClient",
      "PoolId": "$poolId",
      "Region": "$region"
    }
  }
}
```

### GraphQL Schema

<details>

```graphql
// Put your schema below this line


```

</details>

**Comment by tylerjroach** [comment]
Hi @moamenet, you say that you aren't using the CLI, so could you check both your amplifyconfiguration.json and your awsconfiguration.json files and make sure the values match.

For example, for web ui sign ins, v1 almost exclusively uses awsconfiguration.json.
For v2, it only uses amplifyconfiguration.json. 

If you are not using Amplify CLI to update those configuration files, its possible they are not matching and have different values. The awsconfiguration.json file you posted for v1 does not look like a full file, as it does not contain any information in it for web sign ins.

**Comment by moamenet** [comment]
Hi @tylerjroach, I triple checked the files and they do match.
Also both files are exactly the same as which I am using for v1.
How i can be sure: when I build the project with v1, everything works. When intern keep all config files the same and just upgrade the library to v2, I get the exception from above.
So I am sure, that v1 uses the web sign in information from amplifyconfiguration.json as this is the only place the information is present and my entered values are applied.
The amplifyconfiguration.json is btw the same as in the docs: https://docs.amplify.aws/lib/auth/existing-resources/q/platform/android/
As far as I can see, the docs don‘t show any difference between v1 and v2 for this file.
If v2 uses only amplifyconfiguration.json, then why is it failing for v2 and not for v1?

**Comment by PineapplePie** [comment]
@tylerjroach hey, I'm facing the same issue (v2.2.2). All SSO sign-in attempts are failing (for created users with SSO or completely new ones).

In the error callback I've got 
`CodeValidationException{message=invalid_request, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}`

**Comment by PineapplePie** [comment]
Any updates on this? 👀

**Comment by gpanshu** [comment]
@PineapplePie can you help answer @tylerjroach questions as that will help us troubleshoot this.

**Comment by PineapplePie** [comment]
@gpanshu sure! I've partially answered - I've added an error message that was attached to my CodeValidationException - it's simply `invalid_request`.

>Is this before or after you type your username/password.

I'm facing it in both cases. I've cleared all data from the browser, then entered the username and password - got CodeValidationException.
Used already logged in user in the browser (didn't enter any pass/username) - got the same error with the same error message.

Regarding the breakpoint in the `HostedUIClient.fetchToken` - that's a tricky one because I cannot add a breakpoint to any line in the library's classes - not sure why, I can only see the decompiled by Studio kotlin sources, although I'm running the app in a debug mode with a disabled minifyEnabled...

**Comment by tylerjroach** [comment]
@PineapplePie Your issue sounds very similar to https://github.com/aws-amplify/amplify-android/issues/2234, which was fixed in 2.2.2. 

Can you share a bit more about your amplifyconfiguration setup? Are you using appSecret?

**Comment by PineapplePie** [comment]
@tylerjroach I still have the same setup that I mentioned in this particular issue - https://github.com/aws-amplify/amplify-android/issues/2179 and I do have `AppClientSecret` included in my config file, but with the only difference - v2.2.2 instead of 2.0.0. I haven't changed any configurations or console setups. I double-checked the versions and everything.

In the logs I see the next sequence
```
Handling auth redirect response (AuthClient tag)

CodeValidationException{message=invalid_request, cause=null, recoverySuggestion=Sorry, we don't have a suggested fix for this error yet.}
    at com.amplifyframework.auth.cognito.HostedUIClient.fetchToken(HostedUIClient.kt:106)
    at com.amplifyframework.auth.cognito.actions.HostedUICognitoActions$fetchHostedUISignInToken$$inlined$invoke$1.execute(Action.kt:73)
    at com.amplifyframework.statemachine.ConcurrentEffectExecutor$execute$1$1.invokeSuspend(ConcurrentEffectExecutor.kt:26)

Authorization flow completed successfully (AuthClient tag)
```
But unfortunately I cannot debug the exact place and the line of this exception. Maybe there is a way to provide some additional info?

**Comment by tylerjroach** [comment]
@PineapplePie Was 2.0.0 working correctly for you, but 2.2.2 isn't?

**Comment by PineapplePie** [comment]
@tylerjroach v2.0.0 has the same issue, but I just found out the cause of this issue - https://github.com/aws-amplify/amplify-android/issues/2302 that you've created, seems like my SSO users were initialized with emails in the first place a long time ago and then I tried to login with SSO and it didn't work while throwing this misleading error message. Sorry for misunderstanding and taking your time 😢  Are there any plans when the correct error for this case will be released?

**Comment by tylerjroach** [comment]
This is helpful to know. Thank you for your continued research in the issue. I will try and free up some time to dig into that issue.

**Comment by tylerjroach** [comment]
@PineapplePie, I have replicated the issue scenario and will be working on a fix.

**Comment by tylerjroach** [comment]
PR has been merged and should make it in the next Amplify release. You will be able to match the error by checking for:

```
CodeValidationException(
  message = "invalid_request: User already exists with provider user id."
)
```
