### ISSUE TITLE
DataStore initial sync fails when using relations & DynamoDB tables have too many records

### ISSUE THREAD

**Issue by michalisAsp** [aws-amplify/amplify-android#461]
For a schema with types A, B, C and relations:
```
A has a B 
A has a C
```
The above relations create Foreign Key restrictions in SQLite.

The order in which the tables are going to be synced is calculated by TopologicalOrdering I think and that seem to work for a relatively small amount of records.

If in AppSync.DynamoDB we have 10 A  & 10 B & 10 C items, then DataStore will manage at some point to sync everything.

But if we increase the amount to ~ 100 then my app always crashes with Foreign Key Constraint Failure.

I am not 100% sure but what I can see the sync engine is trying to save a type A before all the necessary B & C items are stored locally. Both B & C SQLite tables have at the moment of the crash a subset of the records in DynamoDB. And I cannot see the B & C related items in my DB which are needed to comply with the Foreign Key restriction. Maybe I am missing something? 

**Possible workarounds**
My next step would be to increase the default limit in the resolvers to make sure the sync engine fetches all the records for now or wait for the DataStoreConfiguration to be implemented.

```
Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:43)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:47)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
 E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-2
    java.lang.RuntimeException: com.amplifyframework.datastore.DataStoreException: Error in saving the model: Instance[id=03c486b5-ebe4-447e-876c-a0775f20bacd]
        at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
        at io.reactivex.Completable.blockingAwait(Completable.java:1227)
        at com.amplifyframework.datastore.syncengine.Orchestrator.lambda$start$0$Orchestrator(Orchestrator.java:3)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$Orchestrator$sXOpGcCGs9ZiNIMKtTT6tZMPTQU.run(Unknown Source:2)
        at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at com.amplifyframework.datastore.AWSDataStorePlugin.lambda$null$3(AWSDataStorePlugin.java:1)
        at com.amplifyframework.datastore.-$$Lambda$AWSDataStorePlugin$CfTzVDcGyTSlzFjO5KtLbC_eIGc.accept(Unknown Source:4)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$null$0$SQLiteStorageAdapter(SQLiteStorageAdapter.java:3)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$w4lkRK7kn70UKyGuaWOFqFrETHI.run(Unknown Source:4)
        at io.reactivex.internal.observers.CallbackCompletableObserver.onComplete(CallbackCompletableObserver.java:53)
        at io.reactivex.internal.operators.completable.CompletableFromSingle$CompletableFromSingleObserver.onSuccess(CompletableFromSingle.java:51)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:67)
        at com.amplifyframework.datastore.storage.sqlite.PersistentModelVersion.lambda$null$1(PersistentModelVersion.java:1)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$PersistentModelVersion$3EIFYsUxnq4w1GB5yAimLeipvmc.accept(Unknown Source:6)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:60)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.amplifyframework.datastore.DataStoreException: Error in saving the model: Instance[id=03c486b5-ebe4-447e-876c-a0775f20bacd]
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:91)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:43)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:47)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by jamesonwilliams** [comment]
@michalisAsp Good catch! I _believe_ this is caused by the following:

The "base sync" can be large. If it is, we need to consume paginated responses of sync'd items. Currently, we don't do this, we only consume a first page. Neither does the current implementation inclue _any_ pagination details, when it does the sync request.

As a result, we get an incomplete view of the system. Not all records are synced, right now. Some of the records that come back will refer to things we haven't seen.

@drochetti and I have discussed a few strategies for this, in the past.

One option is to fully consume the paginated sync results, do a topological ordering of them all, and then apply them all:
```
unordered_results: List
while sync query has next page:
    unordered_results <- next page of results

ordered_results <- topological_sort(results)
apply_results_to_db(ordered_results)
```

Another option is to eagerly apply pages of results to the DB, and then keep retrying until all relationships are resolved:

```
sync_complete: boolean
while !sync_complete:
    sync_complete = True
    while sync query has next page:
        try:
            apply_results_to_db(next page of results)
        catch failure:
            sync_complete = False
```

(1) is susceptible to network failures. (2) is fault-tolerant, but a bit wasteful with network calls.

**Comment by michalisAsp** [comment]
I think in general it's better to give feedback to the user as soon as possible. Option 2 sounds better. Although I can't really see what are the extra network calls.

What if in option 1 each time you got a new page you sorted the unordered list and then attempted to store it? Assuming that in the "near" future we could configure the base query with some sorting keys.

**Comment by michalisAsp** [comment]
@jamesonwilliams Hi, I am still seeing this in 1.0

I am still not 100% sure why this is caused but I would like to give a little more detail about how the app behaves and my data set. Hope this helps.

I have > 1000 items in my dynamoDB tables and the local storage in the app is cleared so when the app starts again, DataStore will try to fetch all the data. 

During DataStore initialisation process I am getting multiple foreign key exceptions. Look at the first one below. I don't think there is an issue with my dataset in DynamoDB since this  Instance[id=2574130c-eba0-4b4f-ae32-3df0533b7b3d] has all the required attributes. 

When DataStore initialisation completes with errors, then the data in the SQLite tables look like this:
- instance table has no records. But I have more than 1000 items in dynamoDB
- all the other tables(has one relations for instance) have exactly 100 items. Again I have more than 1000 items in DynamoDB for each type.
- for instance with id=2574130c-eba0-4b4f-ae32-3df0533b7b3d the related items are missing from the other sqlite tables but exist in DynamoDB

Keep in mind that as I mentioned before if I have less than 100 items in dynamoDB, DataStore seems to work fine. 

```
aws-datastore: Storage adapter subscription ended in error
  AmplifyException {message=Error in saving the model: Instance[id=2574130c-eba0-4b4f-ae32-3df0533b7b3d], cause=android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY), recoverySuggestion=See attached exception for details.}
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:89)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.saveModel(SQLiteStorageAdapter.java:38)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$save$3$SQLiteStorageAdapter(SQLiteStorageAdapter.java:47)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$JhGtXoPGeJ7lbNvRHxROfLs-WmE.run(Unknown Source:12) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

I am also seeing more errors likes this one below. Looks to be related. 

```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling |
 AmplifyException {message=Wanted 1 metadata for item with id = 3eee7027-a791-4e75-a7b6-d15cf6ac5381, but had 0., cause=null, recoverySuggestion=This is likely a bug. please report to AWS.}
        at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
        at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
        at com.amplifyframework.datastore.syncengine.VersionRepository.lambda$null$0$VersionRepository(VersionRepository.java:3)
        at com.amplifyframework.datastore.syncengine.-$$Lambda$VersionRepository$R5kiVnQCzDy1jTk4Odil1m_dDtM.accept(Unknown Source:8)
        at com.amplifyframework.datastore.storage.sqlite.SQLiteStorageAdapter.lambda$query$4$SQLiteStorageAdapter(SQLiteStorageAdapter.java:42)
        at com.amplifyframework.datastore.storage.sqlite.-$$Lambda$SQLiteStorageAdapter$rGner20-W7t2tJu4yCrrZwlquWE.run(Unknown Source:10)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by a-melnyk** [comment]
Hi everyone,

I reproduced the problem also for a small number of items (1 Post and 1 Comment) on a schema with [belongs-to connection](https://docs.amplify.aws/cli/graphql-transformer/directives#belongs-to), it seems that DataStore doesn't support this type of connection.

supporting info:
* [logs](https://gist.github.com/a-melnyk/7b02b55d5f88df246c7bfb7a4942f455)
* [code](https://github.com/a-melnyk/simple-datastore/tree/initial_sync_fails_SQLITE_CONSTRAINT_FOREIGNKEY)
* [schema](https://github.com/a-melnyk/simple-datastore/blob/initial_sync_fails_SQLITE_CONSTRAINT_FOREIGNKEY/schema.graphql)

steps to reproduce:
1. start the app and sign in by clicking the corresponding button
2. click the "Post + COMMENT" button, a post and a comment should be created, logged and synchronised to DynamoDB
3. remove the app (and data) from your android device
4. start the app and sign in
5. click the "LIST ALL POSTS" to trigger initial sync, observe application logs -> the initial sync fails

My assumption is that the synchronisation order causes the issue, as we can see from logs and the sqlite state, DataStore tries to synchronise and persist a `Comment` locally without having persisted the corresponding `Post` yet.
Renaming `Comment` entity to `Xomment` seems to change and synchronisation order and fix the issue.

Does it fit in this issue or should I create a new one?

**Comment by jamesonwilliams** [comment]
@a-melnyk This issue is about syncing large amounts of data. Please do create a separate issue for your issues with model connections.

**Comment by jpignata** [comment]
Resolved in 1.3.0. Thanks!

**Comment by micstepper** [comment]
@jpignata are u sure? Using version 1.5.0 im still facing this error?

**Comment by jpignata** [comment]
Hey @micstepper! Can you paste the stack trace? Couple things discussed in this issue so I'd like to narrow down the error.

**Comment by jamesonwilliams** [comment]
Re-closing. @micstepper if you're continuing to have trouble please open a new issue.
